# Generated by Django 5.1.3 on 2024-11-25 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reu',
            fields=[
                ('id', models.CharField(default='cuid', max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oab', models.CharField(max_length=50, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advogado', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Assistente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistente', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Juiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='juiz', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_promotoria', models.CharField(max_length=50, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotor', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.CharField(default='cuid', max_length=36, primary_key=True, serialize=False)),
                ('numero_procedimento', models.CharField(max_length=50, unique=True)),
                ('descricao_procedimento', models.TextField()),
                ('nome_parte', models.CharField(max_length=255)),
                ('comarca', models.CharField(max_length=255)),
                ('classe', models.CharField(blank=True, max_length=255, null=True)),
                ('anexos', models.JSONField(default=list)),
                ('situacao', models.CharField(max_length=50)),
                ('numero_autuacao', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=255)),
                ('data_fato', models.DateField()),
                ('ambiente_agressao', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='processos.advogado')),
                ('assistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='processos.assistente')),
                ('juiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='processos.juiz')),
                ('promotor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='processos.promotor')),
                ('reu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='processos.reu')),
            ],
        ),
    ]
