# Generated by Django 5.1.3 on 2024-11-25 01:31

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='classe',
            field=models.CharField(blank=True, default='Inquerito Civil', max_length=255),
        ),
        migrations.AlterField(
            model_name='processo',
            name='comarca',
            field=models.CharField(default='Acari', max_length=255),
        ),
        migrations.AlterField(
            model_name='processo',
            name='id',
            field=models.CharField(default=cuid.cuid, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reu',
            name='id',
            field=models.CharField(default=cuid.cuid, max_length=36, primary_key=True, serialize=False),
        ),
    ]
