# Generated by Django 5.1.3 on 2024-11-25 00:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualizacao',
            fields=[
                ('id', models.CharField(default='cuid', max_length=36, primary_key=True, serialize=False)),
                ('data_visualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='processos.processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='usuarios.usuario')),
            ],
        ),
    ]
