# Generated by Django 5.1.3 on 2024-11-25 01:31

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizacao',
            name='id',
            field=models.CharField(default=cuid.cuid, max_length=36, primary_key=True, serialize=False),
        ),
    ]
