# Generated by Django 5.1.3 on 2024-11-25 01:31

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, default='assets/images/avatar.webp', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.CharField(default=cuid.cuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
